services:
  - type: web
    name: checkout-pix-service
    env: node
    plan: free
    buildCommand: npm install && pip3 install playwright && playwright install chromium --with-deps
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18
