services:
  - type: web
    name: checkout-mercadopago
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MP_ACCESS_TOKEN
        sync: false
      - key: PORT
        value: 3000
