services:
  - type: web
    name: appmax-checkout
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: APPMAX_TOKEN
        sync: false
      - key: PORT
        value: 3000
